extension_mapping:
    Picture:
        - .jpg
        - .jpeg
        - .png
        - .gif
        - .bmp
    Text:
        - .txt
    Document:
        - .pdf
        - .doc
        - .docx
    Spreadsheet:
        - .xls
        - .xlsx
    Video:
        - .mkv
        - .mp4
        - .mov
        - .flv        
    Others: []
